### ISSUE TITLE
Server Side Code

### ISSUE THREAD

**Issue by tekinc** [ScienceSoft-Inc/DiscountsApp#2]
Anyway to get access to the server side code?

**Comment by ScnAdmin** [comment]
We've just uploaded the latest version of the app (v1.6.10) together with [back-end source code](https://github.com/ScienceSoft-Inc/DiscountsApp/tree/master/SCNDISC.Server) and [front-end admin part](https://github.com/ScienceSoft-Inc/DiscountsApp/tree/master/SCNDISC.FrontEnd/SCNDISC.Admin.UI). Enjoy!

**Comment by tekinc** [comment]
Great, thanks so much...

Is there any documentation available in terms of installation?

**Comment by ScnAdmin** [comment]
Unfortunately there's no documentation. Though the deployment is quite straightforward, you need to publish ASP.NET project to IIS, start MondoDB server and point web.config to the DB instance, besides you might check authentication settings - the server app can work in both anonymous (when the login page accepts whatever creds you input) and "authentication required" modes (e.g. against Active Directory).

**Comment by tekinc** [comment]
got it, thanks again.
