### ISSUE TITLE
Missing css when trying to build UI front end.

### ISSUE THREAD

**Issue by tekinc** [ScienceSoft-Inc/DiscountsApp#4]
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './app.component.css' in 'C:\repos\Discou
ntsApp-master\SCNDISC.FrontEnd\SCNDISC.Admin.UI\src\app'
ERROR in ./src/app/category/category-dialog/category-dialog.component.ts
Module not found: Error: Can't resolve './category-dialog.component.css' in 'C:\
repos\DiscountsApp-master\SCNDISC.FrontEnd\SCNDISC.Admin.UI\src\app\category\cat
egory-dialog'
ERROR in ./src/app/feedback/feedback-dialog/feedback-dialog.component.ts
Module not found: Error: Can't resolve './feedback-dialog.component.css' in 'C:\
repos\DiscountsApp-master\SCNDISC.FrontEnd\SCNDISC.Admin.UI\src\app\feedback\fee
dback-dialog'
ERROR in ./src/app/partner/partner-dialog/partner-dialog.component.ts
Module not found: Error: Can't resolve './partner-dialog.component.css' in 'C:\r
epos\DiscountsApp-master\SCNDISC.FrontEnd\SCNDISC.Admin.UI\src\app\partner\partn
er-dialog'
ERROR in ./src/app/partner/partners-list/partners-list.component.ts
Module not found: Error: Can't resolve './partners-list.component.css' in 'C:\re
pos\DiscountsApp-master\SCNDISC.FrontEnd\SCNDISC.Admin.UI\src\app\partner\partne
rs-list'

Are these css files necessary? 

Thanks!

**Comment by mrserggo** [comment]
No, this files are unnecessery and will be removed in a new version of the application.

Thanks.

**Comment by mrserggo** [comment]
Code is updated to v 1.7.2.

**Comment by ScnAdmin** [comment]
No, this files are unnecessery and will be removed in a new version of the application.
Code is updated to v 1.7.2.
